version: "3.9"

services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - static_volume:/app/build/static
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  react:
    build: ./school_feeding/school
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - static_volume:/app/build/static
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always


volumes:
  static_volume:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /root/School_feeding_last/static_volume
  postgres_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /root/School_feeding_last/postgres_data
