version: "3.9"

services:
  app:
    build: ..
    container_name: app
    restart: always
    volumes:
      - static_volume:/app/build/static
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  static_volume:
    driver: local
