version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: