# Generated by Django 5.0.2 on 2024-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=60, verbose_name="User phone"),
        ),
    ]
