# Generated by Django 5.0.2 on 2024-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateField(
                blank=True, null=True, unique=True, verbose_name="Date Joined"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="Username"
            ),
        ),
    ]
