# Generated by Django 5.0.2 on 2024-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=60, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="Name"
            ),
        ),
    ]
