# Generated by Django 5.0.2 on 2024-03-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_customuser_phone_alter_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Aragatsotn", "Aragatsotn"),
                            ("Ararat", "Ararat"),
                            ("Armavir", "Armavir"),
                            ("Gegharkunik", "Gegharkunik"),
                            ("Kotayk", "Kotayk"),
                            ("Lori", "Lori"),
                            ("Shirak", "Shirak"),
                            ("Syunik", "Syunik"),
                            ("Tavush", "Tavush"),
                            ("Vayots Dzor", "Vayots Dzor"),
                            ("Yerevan", "Yerevan"),
                        ],
                        verbose_name="Մարզ",
                    ),
                ),
                ("town", models.CharField(max_length=100, verbose_name="Գյուղ/Քաղաք")),
                (
                    "school_name",
                    models.CharField(max_length=250, verbose_name="Դպրոցի անուն"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Անուն")),
                ("lastname", models.CharField(max_length=30, verbose_name="Ազգանուն")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Էլեկտրոնային հասցե"
                    ),
                ),
                ("phone", models.BigIntegerField(verbose_name="Հեռախոսի համար")),
                (
                    "team_cat",
                    models.CharField(
                        choices=[
                            ("5-6", "5-6 grades"),
                            ("7-8", "7-8 grades"),
                            (
                                "2-teams",
                                "We have 2 teams of both age groups (5-6 and 7-8 grades)",
                            ),
                        ],
                        verbose_name="Խմբի տեսակ",
                    ),
                ),
                (
                    "project_cat",
                    models.CharField(
                        choices=[
                            (
                                "healthy_lifestyle",
                                'Game on the topic "Healthy lifestyle in a playful way”',
                            ),
                            (
                                "healthy_recipes",
                                '"Tasty and Healthy: My Favorite Healthy Recipes"',
                            ),
                            (
                                "research",
                                'Research on the topic "Discovering the World of Healthy lifestyle: Our Research"',
                            ),
                            (
                                "social_project",
                                "A Social Project “My Healthy Community”",
                            ),
                        ],
                        verbose_name="Պրոեկտի տեսակ",
                    ),
                ),
            ],
        ),
    ]
