# Generated by Django 5.0.2 on 2024-03-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
    ]
