# Generated by Django 5.0.3 on 2024-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='region',
            field=models.CharField(choices=[('Արագածոտն', 'Արագածոտն'), ('Արարատ', 'Արարատ'), ('Արմավիր', 'Արմավիր'), ('Գեղարքունիք', 'Գեղարքունիք'), ('Կոտայք', 'Կոտայք'), ('Լոռի', 'Լոռի'), ('Շիրակ', 'Շիրակ'), ('Սյունիք', 'Սյունիք'), ('Տավուշ', 'Տավուշ'), ('Վայոց Ձոր', 'Վայոց Ձոր'), ('Երևան', 'Երևան')], verbose_name='Մարզ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('Արագածոտն', 'Արագածոտն'), ('Արարատ', 'Արարատ'), ('Արմավիր', 'Արմավիր'), ('Գեղարքունիք', 'Գեղարքունիք'), ('Կոտայք', 'Կոտայք'), ('Լոռի', 'Լոռի'), ('Շիրակ', 'Շիրակ'), ('Սյունիք', 'Սյունիք'), ('Տավուշ', 'Տավուշ'), ('Վայոց Ձոր', 'Վայոց Ձոր'), ('Երևան', 'Երևան')], verbose_name='Մարզ'),
        ),
    ]
