# Generated by Django 5.0.3 on 2024-03-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_registration_region_alter_team_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Անուն')),
                ('email', models.EmailField(max_length=254, verbose_name='Էլ․ հասցե')),
                ('message', models.CharField(max_length=255, verbose_name='Նամակ')),
            ],
            options={
                'verbose_name': 'Նամակ',
                'verbose_name_plural': 'Նամակներ',
            },
        ),
    ]
