# Generated by Django 5.0.3 on 2024-03-19 18:32

import django.core.validators
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_votableitem_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votableitem',
            name='project',
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 1'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img10',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 10'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 2'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 3'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 4'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 5'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 6'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 7'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 8'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='img9',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 9'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='pdf',
            field=models.FileField(default=1, upload_to='', verbose_name='pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votableitem',
            name='project_cat',
            field=models.CharField(choices=[('healthy_lifestyle', 'Game on the topic "Healthy lifestyle in a playful way”'), ('healthy_recipes', '"Tasty and Healthy: My Favorite Healthy Recipes"'), ('research', 'Research on the topic "Discovering the World of Healthy lifestyle: Our Research"'), ('social_project', 'A Social Project “My Healthy Community”')], default=1, verbose_name='Պրոեկտի տեսակ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votableitem',
            name='school_name',
            field=models.CharField(blank=True, null=True, verbose_name='Դպրոց'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='team_cat',
            field=models.CharField(blank=True, choices=[('5-6', '5-6 grades'), ('7-8', '7-8 grades'), ('2-teams', 'We have 2 teams of both age groups (5-6 and 7-8 grades)')], null=True, verbose_name='Խմբի տեսակ'),
        ),
        migrations.AddField(
            model_name='votableitem',
            name='video',
            field=models.FileField(default=1, upload_to='videos/', validators=[main.utils.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'mov'])], verbose_name='Video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votableitem',
            name='word',
            field=models.FileField(default=1, upload_to='', verbose_name='word '),
            preserve_default=False,
        ),
    ]
