# Generated by Django 5.0.3 on 2024-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customuser_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Արագածոտն', 'Արագածոտն'), ('Արարատ', 'Արարատ'), ('Արմավիր', 'Արմավիր'), ('Գեղարքունիք', 'Գեղարքունիք'), ('Կոտայք', 'Կոտայք'), ('Լոռի', 'Լոռի'), ('Շիրակ', 'Շիրակ'), ('Սյունիք', 'Սյունիք'), ('Տավուշ', 'Տավուշ'), ('Վայոց Ձոր', 'Վայոց Ձոր'), ('Երևան', 'Երևան')], verbose_name='Մարզ')),
                ('town', models.CharField(max_length=100, verbose_name='Գյուղ/Քաղաք')),
                ('school_name', models.CharField(max_length=250, verbose_name='Դպրոցի անուն')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Կոնտակտային անձ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Էլեկտրոնային հասցե')),
                ('phone', models.BigIntegerField(verbose_name='Հեռախոսի համար')),
                ('birth', models.DateField(verbose_name='Ծննդյան ամսաթիվ')),
                ('age_cat', models.CharField(max_length=120, verbose_name='Տարիքային խումբ')),
                ('project_cat', models.CharField(max_length=120, verbose_name='Ծրագրի տեսակ')),
            ],
            options={
                'verbose_name': 'Ծրագրի գրանցում',
                'verbose_name_plural': 'Ծրագրի գրանցումներ',
            },
        ),
        # migrations.RemoveField(
        #     model_name='emailverificationtoken',
        #     name='token',
        # ),
    ]
