# Generated by Django 5.0.3 on 2024-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customuser_verification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Օգտատեր', 'verbose_name_plural': 'Օգտատերեր'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Թիմ', 'verbose_name_plural': 'Թմեր'},
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_cat',
        ),
        migrations.RemoveField(
            model_name='project',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_cat',
        ),
        migrations.AddField(
            model_name='project',
            name='name1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն'),
        ),
        migrations.AddField(
            model_name='project',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն'),
        ),
        migrations.AddField(
            model_name='project',
            name='name3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն'),
        ),
        migrations.AddField(
            model_name='project',
            name='name4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն'),
        ),
    ]
