# Generated by Django 5.0.3 on 2024-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_applicationform_remove_emailverificationtoken_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='project_cat',
            new_name='project_cat1',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='project_cat2',
            field=models.CharField(default=1, max_length=120, verbose_name='Ծրագրի տեսակ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='project_cat3',
            field=models.CharField(default=1, max_length=120, verbose_name='Ծրագրի տեսակ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='project_cat4',
            field=models.CharField(default=1, max_length=120, verbose_name='Ծրագրի տեսակ'),
            preserve_default=False,
        ),
    ]
