# Generated by Django 5.0.3 on 2024-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_project_cat_applicationform_project_cat1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='project_cat1',
            field=models.CharField(max_length=120, verbose_name='Ծրագրի տեսակ 1'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='project_cat2',
            field=models.CharField(max_length=120, verbose_name='Ծրագրի տեսակ 2'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='project_cat3',
            field=models.CharField(max_length=120, verbose_name='Ծրագրի տեսակ 3'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='project_cat4',
            field=models.CharField(max_length=120, verbose_name='Ծրագրի տեսակ 4'),
        ),
    ]
