# Generated by Django 5.0.3 on 2024-03-27 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
