# Generated by Django 5.0.3 on 2024-03-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_passwordreset_user_alter_passwordreset_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
