# Generated by Django 5.0.3 on 2024-03-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customuser_options_alter_team_options_and_more'),
        ('main', '0028_passwordchange'),
    ]

    operations = [
    ]

