# Generated by Django 5.0.3 on 2024-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_merge_20240328_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
