# Generated by Django 5.0.3 on 2024-03-29 08:32

import django.core.validators
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_emailverificationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('word', models.FileField(upload_to='words/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt'])], verbose_name='Word')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 5')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 6')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 7')),
                ('img8', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 8')),
                ('img9', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 9')),
                ('img10', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 10')),
                ('pdf', models.FileField(upload_to='', verbose_name='pdf')),
                ('video', models.FileField(upload_to='videos/', validators=[main.utils.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'mov'])], verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Ծրագիր1',
                'verbose_name_plural': 'Ծրագրեր1',
            },
        ),
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('word', models.FileField(upload_to='words/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt'])], verbose_name='Word')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 5')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 6')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 7')),
                ('img8', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 8')),
                ('img9', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 9')),
                ('img10', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 10')),
                ('pdf', models.FileField(upload_to='', verbose_name='pdf')),
                ('video', models.FileField(upload_to='videos/', validators=[main.utils.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'mov'])], verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Ծրագիր2',
                'verbose_name_plural': 'Ծրագրեր2',
            },
        ),
        migrations.CreateModel(
            name='Project3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('word', models.FileField(upload_to='words/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt'])], verbose_name='Word')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 5')),
                ('pdf', models.FileField(upload_to='', verbose_name='pdf')),
                ('video', models.FileField(upload_to='videos/', validators=[main.utils.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'mov'])], verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Ծրագիր3',
                'verbose_name_plural': 'Ծրագրեր3',
            },
        ),
        migrations.CreateModel(
            name='Project4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('name4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Մասնակցի անուն')),
                ('word', models.FileField(upload_to='words/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt'])], verbose_name='Word')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Նկար 5')),
                ('pdf', models.FileField(upload_to='', verbose_name='pdf')),
                ('video', models.FileField(upload_to='videos/', validators=[main.utils.validate_video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'mov'])], verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Ծրագիր4',
                'verbose_name_plural': 'Ծրագրեր4',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
