# Generated by Django 5.0.3 on 2024-03-31 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_passwordresetconfirm_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project3',
            name='pdf_only',
            field=models.FileField(default=1, upload_to='pdf-ppt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF'),
            preserve_default=False,
        ),
    ]
