# Generated by Django 5.0.3 on 2024-04-01 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_project1_team_project2_team_project3_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project4',
            name='pdf_only',
            field=models.FileField(default=1, upload_to='pdf-ppt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF'),
            preserve_default=False,
        ),
    ]
