# Generated by Django 5.0.3 on 2024-04-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_project4_pdf_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project2',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
            preserve_default=False,
        ),
    ]
