# Generated by Django 5.0.3 on 2024-04-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_project2_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project2',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Թիմ'),
        ),
    ]
