# Generated by Django 5.0.3 on 2024-04-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_project1_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project2',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicationform', verbose_name='Թիմ'),
        ),
        migrations.AlterField(
            model_name='project3',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicationform', verbose_name='Թիմ'),
        ),
        migrations.AlterField(
            model_name='project4',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicationform', verbose_name='Թիմ'),
        ),
    ]
