# Generated by Django 5.0.3 on 2024-04-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_project2_team_alter_project3_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.applicationform', verbose_name='Թիմ'),
            preserve_default=False,
        ),
    ]
