# Generated by Django 5.0.3 on 2024-04-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_project1_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicationform', verbose_name='Թիմ'),
        ),
    ]
