# Generated by Django 5.0.3 on 2024-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_project1_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
