# Generated by Django 5.0.4 on 2024-04-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.BigIntegerField(default=1, verbose_name='Հեռախոսահամար'),
            preserve_default=False,
        ),
    ]
