# Generated by Django 5.0.4 on 2024-04-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_applicationform_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1',
            old_name='team',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='team',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project3',
            old_name='team',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project4',
            old_name='team',
            new_name='user',
        ),
    ]
