# Generated by Django 5.0.4 on 2024-04-13 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_rename_team_project1_user_rename_team_project2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
